# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370d456384885bcd062674bdb1bc426bc5f7360fdcee72fb86d4f625cbceb00ed59197334581f28ef32f974aeb3c4e04ade114fbc9e6e007168d66a2fb63aad6

test:
  secret_key_base: 78b9a616e366d27ea7f46a58caad40e67123da25953673f62d65063b171934e94c245a79b2828643a76b80033a8562b831fe6b52af5258f8e1269957df35df65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
